services:
  - type: web
    name: samvaad-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: NVIDIA_NIM_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: HF_TOKEN
        sync: false
